apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: f6clovx9n-python-gitops
  description: This is GitOps manifest for f6clovx9n-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=f6clovx9n-python
    backstage.io/kubernetes-id: f6clovx9n-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: f6clovx9n-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:f6clovx9n-python
